### ISSUE TITLE
Find a way to change repo language from Javascript

### ISSUE THREAD

**Issue by not-fl3** [not-fl3/isalive#8]
We definetly do not use any javascript!

**Comment by cynical89** [comment]
https://github.com/not-fl3/isalive/blob/master/static/main.js

You had almost 10,000 lines of JavaScript in the repo that it was using for linguistics. My PR will remove it.

![image](https://cloud.githubusercontent.com/assets/14186276/19533430/923e56ac-95f4-11e6-9248-9e077cd156ea.png)

**Comment by not-fl3** [comment]
Thanks again!
